//
// SerialChannel_WIN32.h
//
// $Id: //poco/Main/DeviceIO/include/Poco/DeviceIO/Serial/SerialChannel_WIN32.h#1 $
//
// Library: Serial
// Package: Serial
// Module:  SerialChannel
//
// Definition of the SerialChannelImpl class for WIN32.
//
// Copyright (c) 2008, Applied Informatics Software Engineering GmbH.
// and Contributors.
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//


#ifndef Serial_SerialChannel_WIN32_INCLUDED
#define Serial_SerialChannel_WIN32_INCLUDED

#if defined(POCO_OS_FAMILY_WINDOWS)
	#if defined(POCO_WIN32_UTF8)
    // nothing
    #else


#include "Poco/DeviceIO/DeviceIO.h"
#include "Poco/DeviceIO/Serial/SerialConfig_WIN32.h"
#include <windows.h>


namespace Poco {
namespace DeviceIO {
namespace Serial {


class Serial_API SerialChannelImpl
{
protected:
	typedef AutoPtr<SerialConfigImpl> ConfigPtr;

	SerialChannelImpl(SerialConfigImpl* pConfig);
	virtual ~SerialChannelImpl();
	void initImpl();
	void openImpl();
	void closeImpl();
	int readImpl(char* pBuffer, int length);
	int readImpl(char*& pBuffer);
	int writeImpl(const char* buffer, int length);
	const std::string& getNameImpl() const;
	void handleError(const std::string& path);
	static std::string& getErrorText(DWORD errCode, std::string& buf);

private:
	SerialChannelImpl();
	SerialChannelImpl(const SerialChannelImpl&);
	const SerialChannelImpl& operator = (const SerialChannelImpl&);

	HANDLE	  _handle;
	ConfigPtr   _pConfig;
	std::string _leftOver;
};


} } } // namespace Poco::DeviceIO::Serial

    // nothing
    #endif
#elif defined(POCO_OS_FAMILY_UNIX)
// nothing
#endif


#endif // Serial_SerialChannel_WIN32_INCLUDED
