//
// SerialConfig_WIN32.cpp
//
// $Id: //poco/Main/DeviceIO/Serial/src/SerialConfig_WIN32.cpp#1 $
//
// Library: Serial
// Package: Serial
// Module:  SerialConfig
//
// Copyright (c) 2008, Applied Informatics Software Engineering GmbH.
// and Contributors.
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//


#if defined(POCO_OS_FAMILY_WINDOWS)
	#if defined(POCO_WIN32_UTF8)
    // nothing
    #else


#include "Poco/DeviceIO/Serial/SerialConfig_WIN32.h"
#include "Poco/Exception.h"
#include <sstream>


using Poco::InvalidArgumentException;


namespace Poco {
namespace DeviceIO {
namespace Serial {


SerialConfigImpl::SerialConfigImpl(SerialConfigImpl::BPSRateImpl bpsRate,
	DataBitsImpl dataBits,
	char parity,
	StartBitsImpl startBits,
	StopBitsImpl stopBits,
	FlowControlImpl flowControl,
	unsigned char xOnChar,
	unsigned char xOffChar,
	bool useEOF,
	unsigned char eofChar,
	int bufferSize,
	int timeout):  
	_useEOF(useEOF), 
	_bufferSize(bufferSize)
{
	ZeroMemory(&_dcb, sizeof(DCB));

	_dcb.DCBlength = sizeof(DCB);
	_dcb.ByteSize = dataBits;
	_dcb.BaudRate = bpsRate;

	setFlowControlImpl(flowControl, xOnChar, xOffChar);

	setParityCharImpl(parity);
	_dcb.fParity = (('N' != parity) && ('n' != parity));
	_dcb.StopBits = stopBits;

	if (_useEOF) _dcb.EofChar = eofChar;
	
	setTimeoutImpl(timeout);
}


SerialConfigImpl::~SerialConfigImpl()
{
}


void SerialConfigImpl::setFlowControlImpl(SerialConfigImpl::FlowControlImpl flowControl,
		unsigned char xOnChar,
		unsigned char xOffChar)
{
	if (FLOW_CTRL_HARDWARE_IMPL == flowControl)
	{
		_dcb.fOutX = FALSE;
		_dcb.fInX = FALSE;
		_dcb.XonChar = 0;
		_dcb.XoffChar = 0;

		_dcb.fOutxCtsFlow = TRUE;
		_dcb.fOutxDsrFlow = TRUE;
		_dcb.fRtsControl = RTS_CONTROL_HANDSHAKE;
		_dcb.fDtrControl = DTR_CONTROL_HANDSHAKE;
	}
	else if (FLOW_CTRL_SOFTWARE_IMPL == flowControl)
	{
		_dcb.fOutxCtsFlow = FALSE;
		_dcb.fOutxDsrFlow = FALSE;
		_dcb.fRtsControl = RTS_CONTROL_DISABLE;
		_dcb.fDtrControl = DTR_CONTROL_DISABLE;

		_dcb.fOutX = TRUE;
		_dcb.fInX = TRUE;

		setUseXonXoffImpl(xOnChar, xOffChar);
	}
	else
		throw InvalidArgumentException("Invalid argument supplied. Flow control not set.");

	_flowControl = flowControl;
}


void SerialConfigImpl::setUseXonXoffImpl(unsigned char xOnChar,	unsigned char xOffChar)
{
	if (xOnChar != xOffChar)
	{
		_dcb.XonChar = xOnChar;
		_dcb.XoffChar = xOffChar;
	}
	else
		throw InvalidAccessException("XON == XOFF - not set.");
}


void SerialConfigImpl::setXonCharImpl(unsigned char xOn)
{
	poco_assert(FLOW_CTRL_SOFTWARE_IMPL == _flowControl);
	_dcb.XonChar = xOn;
}


void SerialConfigImpl::setXoffCharImpl(unsigned char xOff)
{
	poco_assert(FLOW_CTRL_SOFTWARE_IMPL == _flowControl);
	_dcb.XoffChar = xOff;
}


char SerialConfigImpl::getParityCharImpl() const
{
	switch (_dcb.Parity)
	{
	case PARITY_NONE_IMPL:
		return 'N';
	case PARITY_ODD_IMPL:
		return 'O';
	case PARITY_EVEN_IMPL:
		return 'E';
	case PARITY_MARK_IMPL:
		return 'M';
	case PARITY_SPACE_IMPL:
		return 'S';
	default:
		return 'N';
	}
}


void SerialConfigImpl::setParityCharImpl(char parityChar)
{
	switch (parityChar)
	{
	case 'n': case 'N':
		_dcb.Parity = PARITY_NONE_IMPL; break;

	case 'o': case 'O':
		_dcb.Parity = PARITY_ODD_IMPL; break;

	case 'e': case 'E':
		_dcb.Parity = PARITY_EVEN_IMPL; break;

	case 'm': case 'M':
		_dcb.Parity = PARITY_MARK_IMPL; break;

	case 's': case 'S':
		_dcb.Parity = PARITY_SPACE_IMPL; break;

	default:
		{
			std::ostringstream os;
			os << "SerialConfigImpl::setParityCharImpl(" << parityChar << ')';
			throw InvalidArgumentException(os.str());
		}
	}
}


void SerialConfigImpl::setTimeoutImpl(int timeout)
{
	ZeroMemory(&_cto, sizeof(COMMTIMEOUTS));

	if (timeout > 0)
	{
		_cto.ReadIntervalTimeout = MAXDWORD ;
		_cto.ReadTotalTimeoutMultiplier = MAXDWORD;

		_cto.ReadTotalTimeoutConstant = timeout;
	}
}


} } } // namespace Poco::DeviceIO::Serial

  // nothing
    #endif
#elif defined(POCO_OS_FAMILY_UNIX)
// nothing
#endif

